<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(ClientUnitTestTargetFrameworks)</TargetFrameworks>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yardarm.NodaTime.Client\Yardarm.NodaTime.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FluentAssertions" />
    <Using Include="NodaTime" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
