<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(ClientTargetFrameworks)</TargetFrameworks>
    <OutputType>Library</OutputType>

    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yardarm.Client\Yardarm.Client.csproj" />
  </ItemGroup>

</Project>
