#if !NET11_0_OR_GREATER

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace System.Runtime.CompilerServices;

/// <summary>
/// Provides a common interface for accessing the contents of a union type at runtime.
/// </summary>
/// <remarks>
/// <para>
/// The C# compiler automatically implements this interface on types generated by union declarations.
/// User-defined types annotated with <see cref="UnionAttribute" /> may also implement this interface
/// to provide runtime access to the union's value. Implementing this interface is not required
/// for union behaviors provided by the compiler.
/// </para>
/// </remarks>
/// <seealso cref="UnionAttribute" />
internal interface IUnion
{
    /// <summary>
    /// Gets the value contained in the union, or <see langword="null" /> if the union has no value.
    /// </summary>
    /// <value>
    /// The current value of the union as one of its case types, or <see langword="null" />.
    /// </value>
    object? Value { get; }
}

/// <summary>
/// Indicates that a class or struct is a union type, enabling compiler support for union behaviors.
/// </summary>
/// <remarks>
/// <para>
/// Any class or struct annotated with this attribute is recognized by the C# compiler as a union type.
/// Union types may support behaviors such as implicit conversions from case types, pattern matching
/// that unwraps the union's contents, and switch exhaustiveness checking.
/// </para>
/// </remarks>
/// <seealso cref="IUnion" />
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
internal sealed class UnionAttribute : Attribute
{
}

#endif
