using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Yardarm.Names;

public interface IYardarmTypeInfoProvider
{
    /// <summary>
    /// Gets the name used for the type generated by this type generator, if any.
    /// </summary>
    /// <returns>The name used for the type, or null if the type generator does not generate a type.</returns>
    QualifiedNameSyntax? GetTypeName();

    /// <summary>
    /// Gets the information about the type referenced by this type generator.
    /// </summary>
    /// <remarks>
    /// This information is used to reference the type in other generated code. The <see cref="YardarmTypeInfo.Name"/>
    /// will typically be the name returned by <see cref="GetTypeName"/>.
    /// </remarks>
    YardarmTypeInfo TypeInfo { get; }
}
