<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(YardarmTargetFramework)</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi.YamlReader" />
    <ProjectReference Include="..\Yardarm\Yardarm.csproj" />
    <ProjectReference Include="..\..\NodaTime\Yardarm.NodaTime\Yardarm.NodaTime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Yardarm.CommandLine\swagger.json"
          Link="swagger.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
