<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yardarm.NewtonsoftJson\Yardarm.NewtonsoftJson.csproj" />
    <ProjectReference Include="..\Yardarm.NewtonsoftJson.Client\Yardarm.NewtonsoftJson.Client.csproj" />
  </ItemGroup>

</Project>
