<Project DefaultTargets="Build">
  <Import Project="../Yardarm.Sdk/Sdk/Sdk.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <KeyFile>..\..\Yardarm.snk</KeyFile>

    <!-- Override these for local testing, get directly from build output -->
    <YardarmToolPath>$(MSBuildThisFileDirectory)..\..\artifacts\bin\Yardarm.CommandLine\$(Configuration.ToLower())_any\</YardarmToolPath>
    <YardarmTaskBasePath>$(MSBuildThisFileDirectory)..\..\artifacts\bin\Yardarm.Sdk\$(Configuration.ToLower())\</YardarmTaskBasePath>

    <JsonMode>System.Text.Json</JsonMode>
    <DateTimeMode>Legacy</DateTimeMode>
    <DefaultHttpVersion>2.0</DefaultHttpVersion>
    <DefaultHttpVersionPolicy>RequestVersionOrLower</DefaultHttpVersionPolicy>
    <UnknownDiscriminatorHandling>ReturnNull</UnknownDiscriminatorHandling>
    <ExternallyDiscriminatedUnions>true</ExternallyDiscriminatedUnions>
  </PropertyGroup>

  <Import Project="../Yardarm.Sdk/Sdk/Sdk.targets" />
</Project>
